trigger:
- master

pool:
  vmImage: Ubuntu-16.04

variables:
  imageName: azure-pipelines-canary-k8s/sampleapp
  dockerRegistryConnection: azure-pipelines-canary-acr
  imageRepository: azure-pipelines-canary-k8s/sampleapp
  containerRegistry: ronvincentorg.azurecr.io 
  tag: '$(Build.BuildId)'

stages:
 - stage: Build
   displayName: Build stage
   jobs:
    - job: Build
      displayName: Build
      pool: 
        vmImage: Ubuntu-16.04
      steps:
      - task: Docker@2
        displayName: Build and push image
        inputs:
          containerRegistry: $(dockerRegistryConnection)
          repository: $(imageName)
          command: buildAndPush
          Dockerfile: app/Dockerfile
          tags: |
           $(tag)
      
      - upload: manifests
        artifact: manifests
      
      - upload: misc
        artifact: misc

 - stage: DeployCanary
   displayName: Deploy canary
   dependsOn: Build
   condition: succeeded()

   jobs:
   - deployment: Deploycanary
     displayName: Deploy canary
     pool:
       vmImage: Ubuntu-16.04
     environment: 'akscanary'
     strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: azure-pipelines-canary-acr
              dockerRegistryEndpoint: azure-pipelines-canary-acr

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'deploy'
              strategy: 'canary'
              percentage: '25'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
              imagePullSecrets: azure-pipelines-canary-acr

          - task: KubernetesManifest@0
            displayName: Deploy Forbio and ServiceMonitor
            inputs:
              action: 'deploy'
              manifests: |
                $(Pipeline.Workspace)/misc/*